openapi: 3.0.0
info:
  version: 1.0.0
  title: Chat API
  description: 'Desafio – chat.'
servers:
  - url: 'http://localhost:8086'
    description: 'Testando localmente'
paths:
  /:
    get:
      summary: 'Verifique o status da API'
      operationId: getVersion
      tags: 
        - General
      responses:
        '200':
          description: Quando retornar sucesso será exibida a versão e nome da api.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSuccess'
        x-400|500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'

  /signin:
    post:
      summary: 'Autenticação do usuário'
      description: 'Utilize esta rota para entrar no chat.'
      operationId: postSignIn
      tags:
        - Usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
                
      responses:
        '200':
          description: Retorna o usuário com ID para uso no envio de mensagens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSuccess'
                properties:
                  data:
                    $ref: '#/components/schemas/ResponseSignIn'
        x-400|500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors' 

  /message:
    post:
      summary: 'Enviando uma mensagem'
      operationId: postRegister
      tags:
        - Mensagem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
                
      responses:
        '200':
          description: Retorna a mensagem enviada em caso de sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSuccess'
                properties:
                  data:
                    $ref: '#/components/schemas/ResponseMessage'
        x-400|500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'


  /menssages:
    get:
      summary: 'Lista de todas as mensagens enviadas'
      operationId: getMessages
      tags:
        - Mensagem
      security:
        - bearerAuth: []
        
      responses:
        '200':
          description: Retorna a lista de mensagens enviadas até o momento.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSuccess'
                properties:
                  data:
                    type: array
                    default: []
        x-400|500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'  

                
components:

  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
      
  schemas:
    User:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    Message:
      type: object
      required:
        - message
        - userId
      properties:
        message:
          type: string
        userId:
          type: string
          description: "Obtido no método signIn"
  
    ResponseSignIn:
      type: object
      required:
        - _id
        - name
      properties:
        name:
          type: string
        _id:
          type: string
 
    ResponseMessage:
      type: object
      required:
        - _id
        - message
        - userId
      properties:
        _id:
          type: string
        message:
          type: string
        userId:
          type: string
          
          
    ResponseSuccess:
      type: object
      required:
        - data
        - success
      properties:
        data:
          nullable: true
          oneOf:
            - type: object
            - type: array
        success:
          description: 'Retorna "true" para as requisições de sucesso.'
          type: boolean
            
    ResponseErrors:
      type: object
      required:
        - error
        - success
      properties:
        error:
          type: string
        success:
          description: 'Retorna "false" para as requisições com erro.'
          default: false
          type: boolean